version: '3'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
    volumes:
      - ./data:/app/backend/data
    env_file:
      - .env
    environment:
      - WEBUI_AUTH=True
      - DEFAULT_USER_ROLE=admin
    restart: always
